---
title: "Public_Goods_Cleaning"
author: "Simon van Baal"
date: "19/11/2020"
output: html_document
---

```{r libraries}
library(tidyverse)
#renv::init()
```

```{r loading data files}
exp1RawSurvey <- read_csv('./raw-data/SurveysExperiment1.csv')
exp1RawGame <- read_csv("./raw-data/gameData1.csv")

```


```{r Data Cleaning Experiment 1}
exp1RawSurvey <- 
  exp1RawSurvey %>%
  select(session.code,
         participant.code,
         player.age,
         player.gender,
         player.covid_positive,
         player.location,
         player.attention_check)

exp1RawGame <- 
  exp1RawGame %>%
  filter(session.is_demo == 0) %>%
  select(session.code,
         participant.code,
         participant.payoff,
         subsession.round_number,
         player.id_in_group,
         player.infected,
         player.timeout,
         player.cumulative_earnings,
         player.others_prediction,
         player.contribution,
         player.others_contribution_percentage,
         player.actual_payment,
         player.payoff,
         player.transmission_chance,
         player.second_player_contribution_0,
         player.second_player_contribution_1,
         player.second_player_contribution_2,
         player.second_player_contribution_3,
         player.second_player_contribution_4,
         group.total_contribution,
         group.total_infections,
         group.end_total_infections,
         group.total_earnings,
         group.lockdown,
         group.lockdown_number,
         group.lockdown_cost,
         group.patient_zero_switch)
```

```{r Exclusions on basis of participation}
# Excluding participants who did not finish the experiment.
DNFexp1 <- 
  exp1RawGame %>%
  group_by(session.code, participant.code) %>%
  summarise(cumulativeEarnings = max(player.cumulative_earnings)) %>%
  filter(cumulativeEarnings > 1500, session.code != 'q1uimr6i')

# Check against number of timeouts 
exp1RawGame %>% group_by(participant.code) %>% 
  summarise(nTimeout = sum(player.timeout)) %>% 
  filter(nTimeout > 10)

exp1GameData <- 
  exp1RawGame %>% 
  right_join(DNFexp1, 
             by = c("participant.code", 
                             "session.code")) %>%
  arrange(participant.code, subsession.round_number) %>%
  mutate(lastRoundOthers = lag(player.others_contribution_percentage),
         player.contribution = player.contribution*10,
         player.others_prediction = player.others_prediction*10,
         player.second_player_contribution_0 = player.second_player_contribution_0*10,
         player.second_player_contribution_1 = player.second_player_contribution_1*10,
         player.second_player_contribution_2 = player.second_player_contribution_2*10,
         player.second_player_contribution_3 = player.second_player_contribution_3*10,
         player.second_player_contribution_4 = player.second_player_contribution_4*10
         )

exp1GameData <-
  left_join(exp1GameData,
            exp1RawSurvey,
            by = c("session.code", "participant.code")) %>%
  mutate(Order = factor(
    ifelse(
      subsession.round_number <= 20 &
        group.lockdown_cost == 60 |
        subsession.round_number > 20 &
        group.lockdown_cost == 90,
      "Low Cost First",
      "High Cost First"
    )
  ))

```

```{r Exclusions, include = FALSE}
# Identify participants with low effort responses.

#If participants give the same answers for the hypothetical decisions at least 95% of the time, 
#their hypothetical decisions will be discarded, but the other DVs will be retained. 
#The same applies for the other DVs, where we will remove low-effort responses identified in this way.

# For incentivised self-isolation:
perResponse <-
  exp1RawGame %>%
  filter(group.lockdown == 0) %>%
  group_by(participant.code, player.contribution) %>%
  summarise(n = n()) %>%
  filter(!is.na(player.contribution))

nTrials <- 
  perResponse %>%
  group_by(participant.code) %>%
  summarise(numberOfResponsesIncentivised = sum(n))

toBeExcluded1 <-
  left_join(perResponse, nTrials) %>%
  filter(n >= .95*numberOfResponsesIncentivised)

# For predictions of others' self-isolation
perResponse <- 
  exp1RawGame %>%
  filter(group.lockdown == 0) %>%
  group_by(participant.code, player.others_prediction) %>%
  summarise(n = n()) %>%
  filter(!is.na(player.others_prediction))

nTrials <- 
  perResponse %>% 
  group_by(participant.code) %>%
  summarise(numberOfResponsesPredict = sum(n))

toBeExcluded2 <- 
  left_join(perResponse, nTrials) %>%
  filter(n >= .95*numberOfResponsesPredict)

  
# We will use H2bdata to do the same for the hypotheticals. Borrowing this dataset creation from below.
H2bData <-
  exp1GameData %>%
  filter(group.lockdown == 0) %>%
  pivot_longer(
    cols = c(
      "player.second_player_contribution_0",
      "player.second_player_contribution_1",
      "player.second_player_contribution_2",
      "player.second_player_contribution_3",
      "player.second_player_contribution_4"
    ),
    names_to = "AssumedOthersSelfIsolation",
    values_to = "HypotheticalSelfIsolation"
  ) %>%
  mutate(AssumedOthersSelfIsolation = as.numeric(substr(
    AssumedOthersSelfIsolation,
    start = 35,
    stop = 36
  )))

perResponse <- 
  H2bData %>%
  filter(group.lockdown == 0) %>%
  group_by(participant.code, HypotheticalSelfIsolation) %>%
  summarise(n = n()) %>%
  filter(!is.na(HypotheticalSelfIsolation))

nTrials <- 
  perResponse %>% 
  group_by(participant.code) %>%
  summarise(numberOfResponsesHypothetical = sum(n))

toBeExcluded3 <- 
  left_join(perResponse, nTrials) %>%
  filter(n >= .95*numberOfResponsesHypothetical)
  
# Partial participant exclusions:
  
exp1GameData <-
  exp1GameData %>%
  group_by(participant.code) %>%
  mutate(
    player.contribution = ifelse(
      participant.code %in% toBeExcluded1$participant.code,
      NA,
      player.contribution
    ),
    player.others_prediction = ifelse(
      participant.code %in% toBeExcluded2$participant.code,
      NA,
      player.others_prediction
    ),
    player.second_player_contribution_0 = ifelse(
      participant.code %in% toBeExcluded3$participant.code,
      NA,
      player.second_player_contribution_0
    ),
    player.second_player_contribution_1 = ifelse(
      participant.code %in% toBeExcluded3$participant.code,
      NA,
      player.second_player_contribution_1
    ),
    player.second_player_contribution_2 = ifelse(
      participant.code %in% toBeExcluded3$participant.code,
      NA,
      player.second_player_contribution_2
    ),
    player.second_player_contribution_3 = ifelse(
      participant.code %in% toBeExcluded3$participant.code,
      NA,
      player.second_player_contribution_3
    ),
    player.second_player_contribution_4 = ifelse(
      participant.code %in% toBeExcluded3$participant.code,
      NA,
      player.second_player_contribution_4
    )
  ) %>%
  ungroup()
  
# Full participant exclusions Will be carried out in the hypothesis-bound
# datasets in the _analysis.Rmd.

#rm(perResponse, nTrials, toBeExcluded1, toBeExcluded2, toBeExcluded3)

```



```{r write csv}

write_csv(exp1GameData, './cleaned-data/SelfIsoGameCleaned.csv')

```