---
title: "Public_Goods_Analysis_Pilot"
author: "Simon van Baal"
date: "19/11/2020"
output: html_document
---


This Rmd file contains the analysis of the pilot experiment and the first experiment.
```{r libraries, include = FALSE}
library(tidyverse)
library(afex)
library(ggplot2)
library(ggpubr)
library(emmeans)
library(broom)
library(stargazer)

```


```{r load data, include = FALSE}
publicGoodsData <- read_csv('CleanedPublicGoods.csv') %>%
  filter(subsession.round_number <= 20)
exp1GameData <- read_csv("Exp1PublicGoodsCleaned.csv")

```


```{r Exclusions, include = FALSE}
# Identify participants with low effort responses.

#If participants give the same answers for the hypothetical decisions at least 95% of the time, 
#their hypothetical decisions will be discarded, but the other DVs will be retained. 
#The same applies for the other DVs, where we will remove low-effort responses identified in this way.

# For incentivised self-isolation:
perResponse <-
  exp1GameData %>%
  filter(group.lockdown == 0) %>%
  group_by(participant.code, player.contribution) %>%
  summarise(n = n()) %>%
  filter(!is.na(player.contribution))

nTrials <- 
  perResponse %>%
  group_by(participant.code) %>%
  summarise(numberOfResponsesIncentivised = sum(n))

toBeExcluded1 <-
  left_join(perResponse, nTrials) %>%
  filter(n >= .95*numberOfResponsesIncentivised)

# For predictions of others' self-isolation
perResponse <- 
  exp1GameData %>%
  filter(group.lockdown == 0) %>%
  group_by(participant.code, player.others_prediction) %>%
  summarise(n = n()) %>%
  filter(!is.na(player.others_prediction))

nTrials <- 
  perResponse %>% 
  group_by(participant.code) %>%
  summarise(numberOfResponsesPredict = sum(n))

toBeExcluded2 <- 
  left_join(perResponse, nTrials) %>%
  filter(n >= .95*numberOfResponsesPredict)

  
# We will use H2bdata to do the same for the hypotheticals. Borrowing this dataset creation from below.
H2bData <-
  exp1GameData %>%
  filter(group.lockdown == 0) %>%
  pivot_longer(cols = c("player.second_player_contribution_0", "player.second_player_contribution_1", 
                        "player.second_player_contribution_2", "player.second_player_contribution_3",
                        "player.second_player_contribution_4"),
               names_to = "AssumedOthersSelfIsolation",
               values_to = "HypotheticalSelfIsolation") %>%
  mutate(AssumedOthersSelfIsolation = as.numeric(substr(AssumedOthersSelfIsolation, start = 35, stop = 36)))

perResponse <- 
  H2bData %>%
  filter(group.lockdown == 0) %>%
  group_by(participant.code, HypotheticalSelfIsolation) %>%
  summarise(n = n()) %>%
  filter(!is.na(HypotheticalSelfIsolation))

nTrials <- 
  perResponse %>% 
  group_by(participant.code) %>%
  summarise(numberOfResponsesHypothetical = sum(n))

toBeExcluded3 <- 
  left_join(perResponse, nTrials) %>%
  filter(n >= .95*numberOfResponsesHypothetical)
  
# Partial participant exclusions:
  
exp1GameData <-   
  exp1GameData %>%
    group_by(participant.code) %>%  
    mutate(player.contribution = ifelse(participant.code %in% toBeExcluded1$participant.code, NA, player.contribution),
         player.others_prediction = ifelse(participant.code %in% toBeExcluded2$participant.code, NA, player.others_prediction),
         player.second_player_contribution_0 = ifelse(participant.code %in% toBeExcluded3$participant.code, NA, player.second_player_contribution_0),
         player.second_player_contribution_1 = ifelse(participant.code %in% toBeExcluded3$participant.code, NA, player.second_player_contribution_1),
         player.second_player_contribution_2 = ifelse(participant.code %in% toBeExcluded3$participant.code, NA, player.second_player_contribution_2),
         player.second_player_contribution_3 = ifelse(participant.code %in% toBeExcluded3$participant.code, NA, player.second_player_contribution_3),
         player.second_player_contribution_4 = ifelse(participant.code %in% toBeExcluded3$participant.code, NA, player.second_player_contribution_4)) %>%
  ungroup()
  
# Full participant exclusions Will be carried out in the hypothesis-bound datasets below.

#rm(perResponse, nTrials, toBeExcluded1, toBeExcluded2, toBeExcluded3)

```


```{r Datasets for each hypothesis, include = FALSE}

H1Data <- 
  exp1GameData %>% 
  filter(group.lockdown == 0, group.total_infections < 6,
         !(participant.code %in% toBeExcluded1$participant.code & participant.code %in% toBeExcluded2$participant.code),
         player.timeout != 1) %>%
  mutate(centeredRoundNumber = scale(subsession.round_number, scale = F),
         centeredCases = scale(group.total_infections, scale = F),
         centeredLockdownCost = scale(group.lockdown_cost, scale = F),
         centeredPrediction = scale(player.others_prediction, scale = F),
         centeredLastRoundOthers = scale(lastRoundOthers, scale = F))
# 131 participants: View(H1Data %>% group_by(session.code,participant.code) %>% summarise(n = n()))
# 3ej41aon, eej4bm0z, lui4ds0m were all excluded. 

H2bData <-
  exp1GameData %>%
  filter(group.lockdown == 0,
         !(participant.code %in% toBeExcluded3$participant.code)) %>%
  pivot_longer(cols = c("player.second_player_contribution_0", "player.second_player_contribution_1", 
                        "player.second_player_contribution_2", "player.second_player_contribution_3",
                        "player.second_player_contribution_4"),
               names_to = "AssumedOthersSelfIsolation",
               values_to = "HypotheticalSelfIsolation") %>%
  mutate(AssumedOthersSelfIsolation = as.numeric(substr(AssumedOthersSelfIsolation, start = 35, stop = 36))*10,
         centeredRoundNumber = scale(subsession.round_number, scale = F),
         centeredCases = scale(group.total_infections, scale = F),
         centeredLockdownCost = scale(group.lockdown_cost, scale = F),
         centeredScenario = scale(AssumedOthersSelfIsolation, scale = F),
         centeredLastRoundOthers = scale(lastRoundOthers, scale = F))

H4Data <- 
  exp1GameData %>%
  filter(group.lockdown == 0,
         !(participant.code %in% toBeExcluded1$participant.code & participant.code %in% toBeExcluded2$participant.code & participant.code %in% toBeExcluded3$participant.code)) %>%
  mutate(PredictedHypothetical = ifelse(player.others_prediction == 0, player.second_player_contribution_0,
                                        ifelse(player.others_prediction == 10,player.second_player_contribution_1,
                                               ifelse(player.others_prediction == 20, player.second_player_contribution_2,
                                                      ifelse(player.others_prediction == 30, player.second_player_contribution_3, 
                                                             ifelse(player.others_prediction == 40, player.second_player_contribution_4, NA)))))) %>%
  group_by(participant.code) %>%
  summarise(IncentivisedSelfIsolation = mean(player.contribution, na.rm = T),
            HypotheticalSelfIsolation = mean(PredictedHypothetical, na.rm = T)) %>%
  pivot_longer(cols = c("IncentivisedSelfIsolation", "HypotheticalSelfIsolation"),
               names_to = "Type",
               values_to = "SelfIsolation") %>%
  filter(!is.nan(SelfIsolation)) %>%
  group_by(participant.code) %>%
  filter(n() > 1)

H5Data <-
  exp1GameData %>%
  filter(group.lockdown == 0,
         !(participant.code %in% toBeExcluded1$participant.code & participant.code %in% toBeExcluded2$participant.code & participant.code %in% toBeExcluded3$participant.code)) %>%
  group_by(participant.code, group.lockdown_cost) %>%
  summarise(SelfIsolation = mean(player.contribution, na.rm = T)) %>%
  filter(!is.nan(SelfIsolation))

```


```{r Visualisation Experiment 1}

#====================================================================== H1

infectionData <-
  H1Data %>%
  filter(group.total_infections < 6) %>%
  group_by(group.total_infections) %>%
  summarise(Incentivised_Mean = mean(player.contribution, na.rm = T),
            Incentivised_Ci = sd(player.contribution, na.rm = T)/sqrt(n())*1.96,
            Prediction_Mean = mean(player.others_prediction, na.rm = T),
            Prediction_Ci = sd(player.others_prediction, na.rm = T)/sqrt(n())*1.96) %>%
  pivot_longer(cols = Incentivised_Mean:Prediction_Ci, names_to = c("Type", "Metric"), 
               names_sep = "_", values_to = "Value") %>%
  pivot_wider(names_from = "Metric", values_from = "Value")


predictionIncentivisedPlot <-
  ggplot(infectionData, aes(x = factor(group.total_infections), y = Mean, col = Type, group = Type)) +
  geom_point(position = position_dodge(width = .2)) +
  geom_line(position = position_dodge(width = .2)) +
  geom_errorbar(aes(ymin = Mean-Ci, ymax = Mean+Ci), width = .2,
                position = position_dodge(width = .2)) +
  scale_y_continuous(breaks = c(0, 10, 20, 30, 40), 
                     labels = c('None', 
                                'Slight' , 
                                'Moderate', 
                                'Stringent', 
                                'Complete'), 
                     minor_breaks = c(5, 15, 25, 35),
                     limits = c(0,40),
                     sec.axis = sec_axis(trans=~.*1, name = "Income sacrifice")
                     ) +
  labs(x = "Number of infections", y = "Self-isolation level") +
  scale_color_viridis_d(begin = .3, end = .8) +
  theme_light()

predictionIncentivisedPlot +
  ggsave("predictionIncentivisedPlot.png", width = 6, height = 4)



#====================================================================== H2

#H2a

predictionIncentivisedData <-
  H1Data %>%
  filter(!is.na(player.others_prediction)) %>%
  group_by(player.others_prediction) %>%
  summarise(SelfIsolation = mean(player.contribution, na.rm = T),
            ci = sd(player.contribution, na.rm = T)/sqrt(n())*1.96)


h2aPlot <- 
  ggplot(predictionIncentivisedData, aes(x = player.others_prediction, y = SelfIsolation)) +
  geom_point() +
  geom_errorbar(aes(ymin = SelfIsolation-ci, ymax = SelfIsolation+ci), width = 2) + 
  scale_y_continuous(breaks = c(0, 10, 20, 30, 40), 
                     labels = c('None', 
                                'Slight' , 
                                'Moderate', 
                                'Stringent', 
                                'Complete'), 
                     minor_breaks = c(5, 15, 25, 35),
                     limits = c(0, 40)) +
  scale_x_continuous(breaks = c(0, 10, 20, 30, 40), 
                     labels = c('None', 
                                'Slight' , 
                                'Moderate', 
                                'Stringent', 
                                'Complete'), 
                     minor_breaks = c(5, 15, 25, 35),
                     limits = c(-2, 42)) +
  labs(x = "Prediction of others' behaviour", y = "Incentivised self-isolation") +
  theme_light()


#H2b

predictionHypotheticalData <-
  H2bData %>%
  group_by(AssumedOthersSelfIsolation) %>%
  summarise(Hypothetical = mean(HypotheticalSelfIsolation, na.rm = T),
            ci = sd(HypotheticalSelfIsolation, na.rm = T)/sqrt(n())*1.96)

h2bPlot <-
  ggplot(predictionHypotheticalData, aes(x = AssumedOthersSelfIsolation, y = Hypothetical)) +
  geom_point() +
  geom_errorbar(aes(ymin = Hypothetical-ci, ymax = Hypothetical+ci), width = 2) + 
  scale_y_continuous(breaks = c(0, 10, 20, 30, 40), 
                     labels = c('None', 
                                'Slight' , 
                                'Moderate', 
                                'Stringent', 
                                'Complete'), 
                     minor_breaks = c(5, 15, 25, 35),
                     limits = c(0, 40),
                     sec.axis = sec_axis(trans = ~.*1, name = "Income sacrifice")) +
  scale_x_continuous(breaks = c(0, 10, 20, 30, 40), 
                     labels = c('None', 
                                'Slight' , 
                                'Moderate', 
                                'Stringent', 
                                'Complete'), 
                     minor_breaks = c(5, 15, 25, 35),
                     limits = c(-2, 42)) +
  labs(x = "Others' self-isolation in scenario", y = "Hypothetical self-isolation") +
  theme_light()

ggarrange(h2aPlot, h2bPlot) +
  ggsave("H2Plots.png", height = 4, width = 9, dpi = "print")


#======================================================================= H5

lockdownCostData <-
  H1Data %>%
  filter(group.total_infections < 6) %>%
  group_by(group.lockdown_cost, group.total_infections) %>%
  summarise(SelfIsolation = mean(player.contribution, na.rm = T),
            ci = sd(player.contribution, na.rm = T)/sqrt(n())*1.96)


InfectionsLockdownPlot <- 
  ggplot(lockdownCostData, aes(x = group.total_infections, 
                             y = SelfIsolation, col = factor(group.lockdown_cost))) +
  geom_point(position = position_dodge(width = .2)) +
  geom_line(position = position_dodge(width = .2)) +
  geom_errorbar(aes(ymin = SelfIsolation - ci, ymax = SelfIsolation + ci), width = .2, position = position_dodge(.2)) +
  scale_y_continuous(breaks = c(0, 10, 20, 30, 40), 
                     labels = c('None', 
                                'Slight' , 
                                'Moderate', 
                                'Stringent', 
                                'Complete'), 
                     minor_breaks = c(5, 15, 25, 35),
                     limits = c(0, 40),
                     sec.axis = sec_axis(trans=~.*1)) +
  labs(x = 'Number of infections', y = "Incentivised self-isolation",
       col = 'Cost of Lockdown') +
  scale_colour_viridis_d(begin = .8, end = .1) +
  theme_light()


```



```{r}
###======================== Exploratory Analysis: hypothetical ~ Assumed Self-isolation of others * Lockdown Cost

lockdownCostAssumptionData <-
  H2bData %>%
  filter(!is.na(AssumedOthersSelfIsolation)) %>%
  group_by(group.lockdown_cost, AssumedOthersSelfIsolation) %>%
  summarise(SelfIsolation = mean(HypotheticalSelfIsolation, na.rm = T),
            ci = sd(HypotheticalSelfIsolation, na.rm = T)/sqrt(n())*1.96)


LockdownHypotheticalPlot <-
  ggplot(lockdownCostAssumptionData, 
       aes(x = AssumedOthersSelfIsolation, y = SelfIsolation, col = factor(group.lockdown_cost),
           group = factor(group.lockdown_cost))) +
  geom_point(position = position_dodge(width = 2)) +
  geom_line(position = position_dodge(width = 2)) +
  geom_errorbar(aes(ymin = SelfIsolation - ci, ymax = SelfIsolation + ci), 
                width = 2, position = position_dodge(width = 2)
                ) +
  scale_y_continuous(breaks = c(0, 10, 20, 30, 40), 
                     labels = c('None', 
                                'Slight' , 
                                'Moderate', 
                                'Stringent', 
                                'Complete'), 
                     minor_breaks = c(5, 15, 25, 35),
                     limits = c(0, 40),
                     sec.axis = sec_axis(trans=~.*1)) +
  scale_x_continuous(breaks = c(0, 10, 20, 30, 40), 
                     labels = c('None', 
                                'Slight' , 
                                'Moderate', 
                                'Stringent', 
                                'Complete'), 
                     minor_breaks = c(5, 15, 25, 35),
                     limits = c(-2, 42)) +
  labs(x = "Self-isolation of others in scenario", y = "Hypothetical self-isolation", col = "Cost of Lockdown") +
  scale_colour_viridis_d(begin = .8, end = .1) +
  theme_light()

ggarrange(InfectionsLockdownPlot, LockdownHypotheticalPlot, common.legend = T, legend = "bottom") +
  ggsave("LockdownPlots.png", width  = 8, height = 4)


```


## Each group's responses to lockdowns.


```{r}
lockdownResponseData <-
  exp1GameData %>% 
  group_by(subsession.round_number, session.code, Order) %>%
  summarise(lockdown = mean(group.lockdown),
            lockdownCost = factor(mean(group.lockdown_cost)),
            selfIsolation = mean(player.contribution)) %>%
  mutate(selfIsolation = ifelse(lockdown == 1, NA, selfIsolation))

lockdownPerGroup <-
  lockdownResponseData %>% 
  filter(lockdown > 0)

ggplot(lockdownResponseData, aes(x = subsession.round_number, y = selfIsolation, col = lockdownCost)) +
  geom_point(size = 1) + 
  geom_vline(data = lockdownPerGroup, aes(xintercept = subsession.round_number), 
             col = "dark grey", size = .3) +
  scale_colour_viridis_d(begin = .1, end = .6) +
  labs(x = "Round Number", y = "Incentivised Self-isolation", col = "Cost of Lockdown") +
  scale_y_continuous(breaks = c(0, 1, 2, 3, 4), 
                     labels = c('None', 
                                'Slight' , 
                                'Moderate', 
                                'Stringent', 
                                'Complete'), 
                     minor_breaks = c(.5, 1.5, 2.5, 3.5),
                     limits = c(0,4),
                     sec.axis = sec_axis(trans = ~.*10, name = "Income sacrifice")) +
  theme_light() +
  facet_wrap(~ Order + session.code, nrow = 2) +
  theme(strip.text.x = element_text(margin = margin(2, 0, 2, 0))) +
  ggsave("lockdownResponsePlots.png", width = 10, height = 4)



```




## Table


```{r Table of regression results}
H1DataStargazer <-
  H1Data %>%
  rename(`Incentivised Self-Isolation` = player.contribution,
         `Round Number` = centeredRoundNumber,
         `Number of Infections` = centeredCases,
         `Cost of Lockdown` = centeredLockdownCost,
         `Prediction` = centeredPrediction,
         `Others in Previous Round` = centeredLastRoundOthers,
         `Participant ID` = participant.code)


H1and2aResultsLmer <-
    lmer(`Incentivised Self-Isolation` ~
              `Round Number` +
              `Number of Infections` +
              `Others in Previous Round` +
              `Prediction` +
              (`Round Number`|`Participant ID`),
          data = H1DataStargazer)

class(H1and2aResultsLmer) <- "lmerMod"

H2bDataStargazer <-
  H2bData %>%
  rename(`Hypothetical Self-Isolation` = HypotheticalSelfIsolation,
         `Round Number` = centeredRoundNumber,
         `Number of Infections` = centeredCases,
         `Cost of Lockdown` = centeredLockdownCost,
         `Self-isolation in Scenario` = centeredScenario,
         `Others in Previous Round` = centeredLastRoundOthers,
         `Participant ID` = participant.code)

H2bResultsLmer <-
  lmer(`Hypothetical Self-Isolation` ~
          `Round Number` +
          `Number of Infections` + 
          `Others in Previous Round` +
          `Self-isolation in Scenario` +
          (`Round Number`|`Participant ID`),
        data = H2bDataStargazer)

class(H2bResultsLmer) <- "lmerMod"


H3ResultsLmer <-
  lmer(player.others_prediction ~
          `Round Number` +
          `Number of Infections` +
          `Others in Previous Round` +
          (`Round Number`|`Participant ID`),
        data = H1DataStargazer)

class(H3ResultsLmer) <- "lmerMod"

stargazer(H1and2aResultsLmer, 
          H3ResultsLmer, 
          H2bResultsLmer,
          title = "Regression Results H1-H3",
          out = "regressionTable.htm",
          dep.var.labels = c("Incentivised <br>Self-isolation", "Predictions About <br>Others", "Hypothetical <br>Self-isolation"),
          covariate.labels = c("Round Number",
                               "Number of Infections",
                               "Others in Previous Round",
                               "Prediction",
                               "Assumed Self-isolation <br>of Others"),
          align = TRUE,
          no.space = TRUE)


```

```{r Experiment 1 Analysis for p-values and DFs}
emm_options(pbkrtest.limit = 20000, lmerTest.limit = 20000)

H1and2aResults <-
  mixed(player.contribution ~
          centeredRoundNumber +
          centeredCases +
          centeredPrediction +
          centeredLastRoundOthers +
          (centeredRoundNumber|participant.code),
        data = H1Data)


H2bResults <-
  mixed(HypotheticalSelfIsolation ~
          centeredScenario +
          centeredLastRoundOthers +
          centeredCases +
          centeredRoundNumber +
          (centeredRoundNumber|participant.code),
        data = H2bData,
        method = "S")


H3Results <-
  mixed(player.others_prediction ~
          centeredLastRoundOthers +
          centeredCases +
          centeredRoundNumber +
          (centeredRoundNumber|participant.code),
        data = H1Data)



H4Results <- wilcox.test(SelfIsolation ~ Type, data = H4Data, paired = T, alternative = "greater")


H5Results <- wilcox.test(SelfIsolation ~ group.lockdown_cost, data = H5Data, paired = T, alternative = "less")

emm_options(pbkrtest.limit = 20000)

##============================================== Exploratory analysis

# We will test whether there is an interaction between assumed self-isolation of others and the costliness of lockdown on hypothetical self-isolation. 

ExploratoryAnalysis <- 
  mixed(HypotheticalSelfIsolation ~ 
         AssumedOthersSelfIsolation*group.lockdown_cost + 
         centeredRoundNumber + 
         (1|participant.code), 
       data = H2bData,
       method = "S")

ExploratoryEmmeans <- 
  emtrends(ExploratoryAnalysis, var = "AssumedOthersSelfIsolation", specs = "group.lockdown_cost", lmer.df = "satterthwaite")

# Now we test whether predictions are lower than incentivised self-isolation.

IncentivisedPredictionData <-  
  exp1GameData %>% 
  filter(group.lockdown == 0, group.total_infections < 6,
         !(participant.code %in% toBeExcluded1$participant.code & participant.code %in% toBeExcluded2$participant.code & participant.code %in% toBeExcluded3$participant.code),
         player.timeout != 1) %>% 
  group_by(participant.code) %>%
  summarise(IncentivisedSelfIsolation = mean(player.contribution, na.rm = T),
            Prediction = mean(player.others_prediction, na.rm = T)) %>%
  pivot_longer(cols = c("IncentivisedSelfIsolation", "Prediction"),
               names_to = "Type",
               values_to = "SelfIsolation") %>%
  filter(!is.nan(SelfIsolation)) %>%
  group_by(participant.code) %>%
  filter(n() > 1)

IncentivisedPredictionWilcoxon <-
  wilcox.test(SelfIsolation ~ Type, data = IncentivisedPredictionData, paired = T, alternative = "greater")

```


```{r Results afex}
#H1. Players’ incentivised self-isolation level is higher if the number of infections in the group is higher.
#H2a. Players’ incentivised self-isolation level is lower if their predictions of others’ degree of self-isolation are higher.

summary(H1and2aResults)

# H2b. Players' hypothetical self-isolation level is lower for higher levels of others' self-isolation.

summary(H2bResults)

# H3. Predictions of others' degree of self-isolation will be influenced by the number of total infections in the group. 
#     That is, players infer that with more positive cases, the others are self-isolating to a lower degree.

summary(H3Results)

# H4. Incentivisation decreases self-isolation level. Incentivised self-isolation level is lower than their hypothetical self-isolation level.

H4Results
H4Data %>% 
  group_by(Type) %>%
  summarise(mean = mean(SelfIsolation, na.rm = F),
            median = median(SelfIsolation),
            sd = sd(SelfIsolation, na.rm = F))
qnorm(H4Results$p.value)


# H5. Incentivised self-isolation level is higher when the cost of lockdown is higher.

H5Results
H5Data %>% 
  group_by(group.lockdown_cost) %>%
  summarise(mean = mean(SelfIsolation, na.rm = F),
            median = median(SelfIsolation),
            sd = sd(SelfIsolation, na.rm = F))
qnorm(H5Results$p.value)

# Exploratory Analysis

summary(ExploratoryAnalysis)
pairs(ExploratoryEmmeans, reverse = T)

IncentivisedPredictionWilcoxon
qnorm(IncentivisedPredictionWilcoxon$p.value, lower.tail = F)
IncentivisedPredictionData %>%
  group_by(Type) %>%
  summarise(mean = mean(SelfIsolation),
            median = median(SelfIsolation),
            sd = sd(SelfIsolation))


```



## Pilot materials

```{r Pilot Analysis, eval = FALSE}

PilotLmmContribution <-
  mixed(player.contribution ~
          subsession.round_number +
          group.total_infections +
          factor(player.my_endowment) +
          (subsession.round_number|session.code/participant.code),
        data = publicGoodsData)
nice(lmmContribution)



```



```{r Figures for visualisation, eval = FALSE}
ggplot(publicGoodsData, aes(x = player.contribution, 
                            fill = group.condition)) +
  geom_density(alpha = .4) +
  labs(x = 'Contribution', y = 'Density')

ggplot(publicGoodsData %>% filter(player.my_endowment != 160 & player.my_endowment != 240) %>% mutate(Endowment = factor(player.my_endowment)),
       aes(x = player.contribution,
           fill = Endowment)) +
  geom_density(alpha = .4) +
  labs(x = 'Contribution', y = 'Density')



ggplot(publicGoodsData %>%
         group_by(subsession.round_number) %>%
         summarise(lockdown = mean(group.lockdown)),
       aes(x = subsession.round_number, y = lockdown)) +
  geom_point()

ggplot(publicGoodsData %>% 
         filter(group.total_infections < 6) %>%
         mutate(Infections = factor(group.total_infections),
                Contribution = player.contribution),
       aes(x = Infections,
           y = Contribution,
           fill = Infections)) +
  geom_violin() +
  scale_fill_viridis_d(end = .9) +
  theme_light()

#============================== C-game: Self-isolation by cases in group

ggplot(publicGoodsData %>%
         filter(group.total_infections < 6, player.second_player_contribution_0 != 5) %>%
         mutate(`Cases in group` = as.numeric(group.total_infections)) %>%
         group_by(`Cases in group`) %>%
         summarise(`Self-isolation` = mean(player.contribution, na.rm = T),
                   lowerCi = `Self-isolation` - 1.96*sd(player.contribution, na.rm = T)/sqrt(n()),
                   upperCi = `Self-isolation` + 1.96*sd(player.contribution, na.rm = T)/sqrt(n())),
       aes(x = `Cases in group`, y = `Self-isolation`)) +
  geom_point() +
  geom_line() +
  geom_errorbar(aes(ymin = lowerCi, ymax = upperCi), width = .1) +
  labs(title = 'Incentivised self-isolation by number of infections',
       x = 'Number of infections in group',
       y = 'Incentivised self-isolation') +
  scale_y_continuous(breaks = c(0, 1, 2, 3, 4), 
                     labels = c('None (0)', 
                                'Slight (1)' , 
                                'Moderate (2)', 
                                'Stringent (3)', 
                                'Complete (4)'), 
                     minor_breaks = c(.5, 1.5, 2.5, 3.5),
                     limits = c(0,4)) +
  theme_light()

ggplot(publicGoodsData %>%
         filter(player.second_player_contribution_0 != 5) %>% 
         group_by(session.code, subsession.round_number) %>%
         summarise(`Self-isolation` = mean(player.contribution)) %>%
         ungroup() %>%
         arrange(subsession.round_number) %>% 
         mutate(`Average self-isolation in previous round` = ),
       aes(x = `Self-isolation`,
           y = `Average self-isolation in previous round`)) +
  geom_point()

#============================= round number stuff
ggplot(publicGoodsData %>% 
         group_by(subsession.round_number) %>%
         summarise(`Self-isolation` = mean(player.contribution, na.rm = T)) %>%
         rename(`Round Number` = subsession.round_number), 
       aes(x = `Round Number`,
           y = `Self-isolation`)) +
  geom_point() +
  geom_smooth() +
  scale_y_continuous(breaks = c(0, 1, 2, 3, 4), 
                     labels = c('None (0)', 
                                'Slight (1)' , 
                                'Moderate (2)', 
                                'Stringent (3)', 
                                'Complete (4)'), 
                     minor_breaks = c(.5, 1.5, 2.5, 3.5),
                     limits = c(0,4)) +
  theme_light() +
  theme(axis.text = element_text(size = 7))

# ggplot(publicGoodsData %>% 
#          group_by(subsession.round_number, group.condition) %>%
#          summarise(player.contribution = mean(player.contribution, na.rm = T)), 
#        aes(x = subsession.round_number,
#            y = player.contribution,
#            colour = group.condition)) +
#   geom_point() +
#   geom_smooth() +
#   lims(y = c(0,4)) +
#   theme_light()



```


```{r P Game figures, eval = FALSE}

pGameOthers #  <-
  ggplot(publicGoodsData %>% 
         filter(player.second_player_contribution_0 != 5) %>% 
         summarise(SecondPlayer0 = mean(player.second_player_contribution_0, na.rm = T),
                              lowerciSecondPlayer0 = SecondPlayer0 - 1.96*(sd(player.second_player_contribution_0, na.rm = T)/sqrt(n())),
                              upperciSecondPlayer0 = SecondPlayer0 + 1.96*(sd(player.second_player_contribution_0, na.rm = T)/sqrt(n())),
                              SecondPlayer1 = mean(player.second_player_contribution_1, na.rm = T),
                              lowerciSecondPlayer1 = SecondPlayer1 - 1.96*(sd(player.second_player_contribution_1, na.rm = T)/sqrt(n())),
                              upperciSecondPlayer1 = SecondPlayer1 + 1.96*(sd(player.second_player_contribution_1, na.rm = T)/sqrt(n())),
                              SecondPlayer2 = mean(player.second_player_contribution_2, na.rm = T),
                              lowerciSecondPlayer2 = SecondPlayer2 - 1.96*(sd(player.second_player_contribution_2, na.rm = T)/sqrt(n())),
                              upperciSecondPlayer2 = SecondPlayer2 + 1.96*(sd(player.second_player_contribution_2, na.rm = T)/sqrt(n())),
                              SecondPlayer3 = mean(player.second_player_contribution_3, na.rm = T),
                              lowerciSecondPlayer3 = SecondPlayer3 - 1.96*(sd(player.second_player_contribution_3, na.rm = T)/sqrt(n())),
                              upperciSecondPlayer3 = SecondPlayer3 + 1.96*(sd(player.second_player_contribution_3, na.rm = T)/sqrt(n())),
                              SecondPlayer4 = mean(player.second_player_contribution_4, na.rm = T),
                              lowerciSecondPlayer4 = SecondPlayer4 - 1.96*(sd(player.second_player_contribution_4, na.rm = T)/sqrt(n())),
                              upperciSecondPlayer4 = SecondPlayer4 + 1.96*(sd(player.second_player_contribution_4, na.rm = T)/sqrt(n()))) %>%
  pivot_longer(cols = everything(), names_to = c('Conditional'), values_to = c('Values')) %>%
  mutate(number = rep(c(0,1,2,3,4), each = 3),
         Conditional = rep(c("Contribution", "lowerCi", "upperCi"), times = 5)) %>%
  pivot_wider(id = 'number', names_from = 'Conditional', values_from = 'Values') %>%
  rename(`Others' self-isolation` = number,
         `Self-isolation` = Contribution),
  aes(x = `Others' self-isolation`, 
      y = `Self-isolation`)) +
  geom_point() +
  geom_line() +
  geom_errorbar(aes(ymin=lowerCi, ymax=upperCi), colour="black", width=.1) +
  scale_x_continuous(breaks = c(0, 1, 2, 3, 4), labels = c('None (0)', 'Slight (1)', 'Moderate (2)', 'Stringent (3)', 'Complete (4)')) +
  scale_y_continuous(breaks = c(0, 1, 2, 3, 4), 
                     labels = c('None (0)', 
                                'Slight (1)' , 
                                'Moderate (2)', 
                                'Stringent (3)', 
                                'Complete (4)'), 
                     minor_breaks = c(.5, 1.5, 2.5, 3.5),
                     limits = c(0,4)) +
  labs(title = 'Hypothetical self-isolation conditional on average contribution in group',
       y = 'Hypothetical self-isolation',
       x = 'Assumed self-isolation of others') +
  theme_light() +
  theme(axis.text = element_text(size = 7))

pGameInfections <- 
  ggplot(publicGoodsData %>%
         filter(player.second_player_contribution_0 != 5) %>%
         group_by(group.total_infections) %>%
         summarise(`Self-isolation` = mean(c(player.second_player_contribution_0,
                                         player.second_player_contribution_1,
                                         player.second_player_contribution_2,
                                         player.second_player_contribution_3,
                                         player.second_player_contribution_4)),
                   lowerCi = `Self-isolation` -
                     1.96*sd(c(player.second_player_contribution_0,
                                         player.second_player_contribution_1,
                                         player.second_player_contribution_2,
                                         player.second_player_contribution_3,
                                         player.second_player_contribution_4))/sqrt(n()*5), #multiply n by five as averaging over 5 cols
                   upperCi = `Self-isolation` +
                     1.96*sd(c(player.second_player_contribution_0,
                                         player.second_player_contribution_1,
                                         player.second_player_contribution_2,
                                         player.second_player_contribution_3,
                                         player.second_player_contribution_4))/sqrt(n()*5)) %>%
         rename(`Number of cases in group` = group.total_infections),
       aes(x = `Number of cases in group`, y = `Self-isolation`)) +
  geom_point() +
  geom_line() +
  #geom_ribbon(aes(ymin = lowerCi, ymax = upperCi), alpha = .1) +
  geom_errorbar(aes(ymin=lowerCi, ymax=upperCi), colour="black", width=.1) +
  labs(title = 'Hypothetical self-isolation by number of cases in group', y = ' ') +
  theme_light() +
  scale_y_continuous(breaks = c(0, 1, 2, 3, 4), 
                     labels = NULL, 
                     minor_breaks = c(.5, 1.5, 2.5, 3.5),
                     limits = c(0,4)) +
  theme(axis.text = element_text(size = 7))

ggarrange(pGameOthers, pGameInfections) +
  ggsave("pGamePlots.png", width = 12, height = 5)




```


```{r second player comparison, eval = FALSE}

a <- ggplot(publicGoodsData %>% filter(!is.na(player.second_player_contribution_0)), 
       (aes(x = factor(player.second_player_contribution_0), y = player.contribution, col = group.total_infections))) +
  geom_jitter(height = .3, width = .3) +
  scale_colour_viridis_c(begin = 0, end = .85) +
  labs(x = 'Response if Second Player Contribution = No Self-Isolation', 
       y = 'Actual Response',
       col = 'Number of infections') +
  theme_light()
b <- ggplot(publicGoodsData %>% filter(!is.na(player.second_player_contribution_1)), 
       (aes(x = factor(player.second_player_contribution_1), y = player.contribution, col = group.total_infections))) +
  geom_jitter(height = .3, width = .3) +
  scale_colour_viridis_c(begin = 0, end = .85) +
  labs(x = 'Response if Second Player Contribution = Slight Self-Isolation', 
       y = 'Actual Response',
       col = 'Number of infections') +
  theme_light()
c <- ggplot(publicGoodsData %>% filter(!is.na(player.second_player_contribution_2)), 
       (aes(x = factor(player.second_player_contribution_2), y = player.contribution, col = group.total_infections))) +
  geom_jitter(height = .3, width = .3) +
  scale_colour_viridis_c(begin = 0, end = .85) +
  labs(x = 'Response if Second Player Contribution = Moderate Self-Isolation', 
       y = 'Actual Response',
       col = 'Number of infections') +
  theme_light()
d <- ggplot(publicGoodsData %>% filter(!is.na(player.second_player_contribution_3)), 
       (aes(x = factor(player.second_player_contribution_3), y = player.contribution, col = group.total_infections))) +
  geom_jitter(height = .3, width = .3) +
  scale_colour_viridis_c(begin = 0, end = .85) +
  labs(x = 'Response if Second Player Contribution = Stringent Self-Isolation', 
       y = 'Actual Response',
       col = 'Number of infections') +
  theme_light()
e <- ggplot(publicGoodsData %>% filter(!is.na(player.second_player_contribution_4)), 
       (aes(x = factor(player.second_player_contribution_4), y = player.contribution, col = group.total_infections))) +
  geom_jitter(height = .3, width = .3) +
  scale_colour_viridis_c(begin = 0, end = .85) +
  labs(x = 'Response if Second Player Contribution = Complete Self-Isolation', 
       y = 'Actual Response',
       col = 'Number of infections') +
  theme_light()

ggarrange(a, b, c, d, e) +
  ggsave('SecondPlayerPlots.png', width = 18, height = 8)
  


```




```{r Descriptives, eval = FALSE}

View(publicGoodsData %>% filter(group.total_infections < 6) %>% group_by(group.condition, group.total_infections) %>% summarise(lockdown = mean(player.contribution, na.rm = T)))

publicGoodsData %>% 
  filter(group.total_infections < 6) %>% 
  group_by(group.total_infections) %>% 
  summarise(`Second Player Contribution - None` = mean(player.second_player_contribution_0, na.rm = T),
            `Second Player Contribution - Slight` = mean(player.second_player_contribution_1, na.rm = T),
            `Second Player Contribution - Moderate` = mean(player.second_player_contribution_2, na.rm = T),
            `Second Player Contribution - Stringent` = mean(player.second_player_contribution_3, na.rm = T),
            `Second Player Contribution - Complete` = mean(player.second_player_contribution_4, na.rm = T))

```


```{r Role splitting, eval = FALSE}

rolesData <- 
  publicGoodsData %>%
  group_by(participant.code, subsession.round_number) %>%
  summarise(secondPlayer0 = mean(player.second_player_contribution_0, na.rm = T),
            secondPlayer1 = mean(player.second_player_contribution_1, na.rm = T),
            secondPlayer2 = mean(player.second_player_contribution_2, na.rm = T),
            secondPlayer3 = mean(player.second_player_contribution_3, na.rm = T),
            secondPlayer4 = mean(player.second_player_contribution_4, na.rm = T)) %>%
  pivot_longer(cols = secondPlayer0:secondPlayer4,
               names_to = "Self-isolation of others",
               values_to = "Self-isolation") %>%
  mutate(`Self-isolation of others` = rep(c(0,1,2,3,4), times = 20))


nested <- rolesData %>% 
  nest(data = -participant.code)

nested <- 
  nested %>% 
  mutate(
    test = map(data, ~ cor.test(.x$`Self-isolation of others`, .x$`Self-isolation`, method = 'spearman')), # S3 list-col
    tidied = map(test, tidy)
  )  %>%
  unnest(tidied) %>%
  filter(estimate > 0, p.value < .05)

#rolesData %>% group_by(participant.code) %>% summarise(selfIso = mean(`Self-isolation`, na.rm = T)) %>% filter(selfIso == 0)
# no participant is a strict free rider
#publicGoodsData %>% group_by(participant.code) %>% summarise(selfIso = mean(player.contribution, na.rm = T)) %>% filter(selfIso == 0)
# neither in the c-game

triangleContributorData <- 
  rolesData %>%
  group_by(participant.code, `Self-isolation of others`) %>%
  summarise(`Self-isolation` = mean(`Self-isolation`, na.rm = T)) %>%
  pivot_wider(id_cols = participant.code,
              names_from = "Self-isolation of others",
              names_prefix = "Others",
              values_from = "Self-isolation") %>%
  mutate(triangleContributor = ifelse(Others3 > Others4 & Others3 > Others2 & Others3 > Others1 & Others3 > Others0, T,
                                      ifelse(Others2 > Others0 & Others2 > Others1 & Others2 > Others3 & Others2 > Others4, T, 
                                             ifelse(Others1 > Others0 & Others1 > Others2 & Others1 > Others3 & Others1 > Others4, T, F)))) %>%
  filter(triangleContributor == T)



```

