---
title: "Self-Isolation Game Modelling"
author: "Simon van Baal"
date: "21/05/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(data.table)
library(ggpubr)

```


```{r Parameters, warning=FALSE}

HighIncomeLockdown = 40
LowIncomeLockdown = 10

# Possible strategies given here:
OwnStrategies <- c("Moderate to None",
    "Moderate to Complete",
    "Unconditional Cooperator",
    "Stringent Cooperator",
    "Moderate Cooperator",
    "Slight Cooperator",
    "Defector")


```


```{r New version}
SelfIsolationGame <- function(LockdownIncome, OwnStrategies, GroupStrategies, nSims = 100) {
  nPlayers = 11
  lockdownThreshold = 6
  nRounds = 20
  
# Populate the final dataset for output.
  Results <- 
    data.table(
      SimulationNumber = rep(rep(seq(1:nSims), each = 11), times = length(OwnStrategies)),
      PlayerNumber = rep(rep(seq(1:11), times = nSims), times = length(OwnStrategies)),
      Strategies = rep(NA, times = nSims*length(OwnStrategies)),
      CumulativeIncomes = rep(NA, times = nSims*length(OwnStrategies)),
      OwnStrategy = rep(OwnStrategies, each = nSims*11)
    )
  
  
  for (s in 1:length(OwnStrategies)) {
    
    Strategies <- c(OwnStrategies[s], GroupStrategies)
  
    for (n in 1:nSims) {
    
      lockdown <- c() # Create empty list for checking whether there is a lockdown.
      patientZeroSwitch <- c(0) # Indicate that a new patient zero has been picked from the beginning.
      nInfections <- c()
      
        #Populate a data table with the inputs
        Incomes <- data.table(
        Players = rep(c("Player1", "Player2",
                    "Player3", "Player4",
                    "Player5", "Player6",
                    "Player7", "Player8",
                    "Player9", "Player10",
                    "Player11"), times = 21),
        PlayerStrategy = Strategies,
        Variable = c(rep(paste0("Round_", seq(1:20)), each = 11), rep("Cumulative_Earnings", 11)),
        Income = 0)
        
        # Infect patient zero
        Infections <- data.table(
        Players = rep(c("Player1", "Player2",
                    "Player3", "Player4",
                    "Player5", "Player6",
                    "Player7", "Player8",
                    "Player9", "Player10",
                    "Player11"), times = 20),
        PlayerStrategy = Strategies,
        SelfIsolation = 0,
        RoundNumber = rep(seq(1:20), each = 11),
        Infected = 0,
        Infectiousness = 0)
        
        patientZero <- sample(Infections$Players, 1)
        
        Infections <- 
          Infections %>% 
          mutate(Infected = ifelse(Players == patientZero & RoundNumber == 1, 1, 
                                   ifelse(Players != patientZero & RoundNumber == 1, 0, NA)))
      
      #============================================ Each round we determine the number of infections, lockdown, and income
      
      for (round in 1:nRounds) {
        
        nInfections <- 
          append(nInfections, sum(Infections %>% filter(RoundNumber == round) %>% select(Infected)))
        
        
        ##====================================== Determine whether the group is in lockdown
        if (nInfections[round] < lockdownThreshold) { # If there are <6 infections:
          
          lockdown <- append(lockdown, 0) # Not lockdown
          
          if (round > 3) {
            
            if(nInfections[round - 1] == 1 & 
               nInfections[round - 2] == 1 &
               nInfections[round - 3] == 1 &
               patientZeroSwitch[round-2] != 1 &
               patientZeroSwitch[round-1] != 1 &
               patientZeroSwitch[round] != 1) { # If there have been no new infections, nor any patient zero switches:
              
               #Infect a new person
              patientZero <- sample(Infections$Players, 1)
              Infections <- 
                Infections %>% 
                mutate(Infected = ifelse(Players == patientZero & RoundNumber == round, 1, 
                                  ifelse(Players != patientZero & RoundNumber == round, 0, Infected))) # Appoint new infected person for after lockdown
              patientZeroSwitch <- append(patientZeroSwitch, 1)
              } else {
            patientZeroSwitch <- append(patientZeroSwitch, 0)
              }
          } else {
              patientZeroSwitch <- append(patientZeroSwitch, 0)
            }
        
        } else if (nInfections[round] >= lockdownThreshold &
                   lockdown[round - 1] != 1) { # If there are 6 infections, and the last round was not a lockdown round:
          
          lockdown <- append(lockdown, 1) # Then lockdown: first round.
          
            if (round < 20) {
              Infections$Infected[(1+(round)*11):(11+(round)*11)] <- Infections$Infected[(1+(round-1)*11):(11+(round-1)*11)]
              }
          
          patientZeroSwitch <- append(patientZeroSwitch, 0) # We'll indicate the switch at the end of the lockdown.
        
        } else if (lockdown[round - 1] == 1 & 
                   lockdown[round - 2] == 0) { #If >6 the last round was a lockdown round, but the one before was not:
          
          lockdown <- append(lockdown, 1) # lockdown round 2
    
          
          patientZero <- sample(Infections$Players, 1)
          Infections <- 
            Infections %>% 
                mutate(Infected = ifelse(Players == patientZero & RoundNumber == round + 1, 1, 
                                  ifelse(Players != patientZero & RoundNumber == round + 1, 0, Infected))) # Appoint new infected person for after lockdown
          
          patientZeroSwitch <- append(patientZeroSwitch, 0)
          
        
        } else if (lockdown[round - 1] == 1 & 
                   lockdown[round - 2] == 1) { #If we already had 2 lockdown rounds:
          
          lockdown <- append(lockdown, 0) # No longer in lockdown
          patientZeroSwitch <- append(patientZeroSwitch, 1) # To indicate that we are playing with a new patient zero after lockdown.
          
          # Copy infections from previous rounds.
          Infections$Infected[(1+(round-1)*11):(11+(round-1)*11)] <- Infections$Infected[(1+(round-2)*11):(11+(round-2)*11)]
          
        }
        
        ##======================================= Determine whether players are infected
        
        if (lockdown[round] == 0) { # If not in lockdown
          
          #Specify players' actions each round based on their strategy

          
          Infections$SelfIsolation[(1+(round-1)*11):(11+(round-1)*11)] <- 
            ifelse(Infections$PlayerStrategy[(1+(round-1)*11):(11+(round-1)*11)] == "Unconditional Cooperator", 
                               1, # Full protection because of full self-isolation
            ifelse(Infections[(1+(round-1)*11):(11+(round-1)*11),2] == "Stringent Cooperator", 
                                      .75,
            ifelse(Infections[(1+(round-1)*11):(11+(round-1)*11),2] == "Moderate Cooperator", 
                                             .5,
            ifelse(Infections[(1+(round-1)*11):(11+(round-1)*11),2] == "Slight Cooperator", 
                                                    .25,
            ifelse(Infections[(1+(round-1)*11):(11+(round-1)*11),2] == "Defector", 
                                                           0, 
            ifelse(Infections$PlayerStrategy[(1+(round-1)*11):(11+(round-1)*11)] == "Moderate to Complete", 
                   ifelse(nInfections[round] == 1, .5,
                                                                                                                                                               ifelse(nInfections[round] == 2, .5,
                                                                                                                                                                      ifelse(nInfections[round] == 3, 1,
                                                                                                                                                                             ifelse(nInfections[round] == 4, 1,
                                                                                                                                                                                    ifelse(nInfections[round] >= 5, 1, 1))))), 
             ifelse(Infections$PlayerStrategy[(1+(round-1)*11):(11+(round-1)*11)] == "Moderate to None", 
                    ifelse(nInfections[round] == 1, .5, 
                           ifelse(nInfections[round] == 2, .5, 
                                  ifelse(nInfections[round] == 3, 0,
                                         ifelse(nInfections[round] == 4, 0, 
                                                ifelse(nInfections[round] >= 5, 0, 1))))), 
                    NA)))))))
        
          # Insert chance of transmission for each action of infected people.
          Infections$Infectiousness[(1+(round-1)*11):(11+(round-1)*11)] <-
            ifelse(Infections$Infected[(1+(round-1)*11):(11+(round-1)*11)] == 1, 
                             1-Infections$SelfIsolation[(1+(round-1)*11):(11+(round-1)*11)], 
                             0) 
          
          # Set limit to transmission risk for other players
          TransmissionPool <- 
            ifelse(sum(Infections$Infectiousness[(1+(round-1)*11):(11+(round-1)*11)]) <= 1, 
                                     sum(Infections$Infectiousness[(1+(round-1)*11):(11+(round-1)*11)]),
                                     1)
        if (round < 20) {
            # Determine whether disease is transmitted
            Infections$Infected[(1+(round)*11):(11+(round)*11)] <- # Determine infections for next round 
              ifelse(Infections$Infected[(1+(round-1)*11):(11+(round-1)*11)] == 0, # If the person was not infected 
                     rbinom(11, 1, (1 - Infections$SelfIsolation[(1+(round-1)*11):(11+(round-1)*11)]) * TransmissionPool), 
                     #Infect with probability (1-SelfIsolation) * TransmissionPool, example: Slight self-isolation, TransmissionPool is 1, rbinom(1,1,.75)
                     Infections$Infected[(1+(round-1)*11):(11+(round-1)*11)] # Else, preserve infection
                     )
        }
          
        } else if (lockdown[round] == 1) { # If in lockdown
          
          Infections$SelfIsolation[(1+(round-1)*11):(11+(round-1)*11)] <- 
            rep(NA, 11)
          
          Infections$Infectiousness[(1+(round-1)*11):(11+(round-1)*11)] <-
            rep(NA, 11)
                      
        }
        
        #=============================================== Set payoffs based on lockdown yes/no
          
          
        # Insert incomes
        Incomes$Income[(1+(round-1)*11):(11+(round-1)*11)] <-
          ifelse(!is.na(Infections$SelfIsolation[(1+(round-1)*11):(11+(round-1)*11)]), 
                 100 - 40 *Infections$SelfIsolation[(1+(round-1)*11):(11+(round-1)*11)],
            LockdownIncome)
          }
      
      # Set cumulative income for each player after finishing the game.
      Incomes[Variable == "Cumulative_Earnings", 'Income'] <- 
        Incomes[Variable != "Cumulative_Earnings", sum(Income), Players][, V1]
      
      Results$CumulativeIncomes[(((s-1)*nSims*11)+(1+(n-1)*11)):(((s-1)*nSims*11)+(11+(n-1)*11))] <- 
        Incomes$Income[221:231]
      Results$Strategies[(((s-1)*nSims*11)+(1+(n-1)*11)):(((s-1)*nSims*11)+(11+(n-1)*11))] <-
        Incomes$PlayerStrategy[1:11]
    }
  }
  # Push results to global environment
  #returnList <- list(Incomes, Infections, nInfections)
  return(Results)
}
```


```{r Run the Game}

# Example
#SelfIsolationGame(HighIncomeLockdown, OwnStrategies, c(rep("Defector", 10)))

set.seed(123)

# Running for loop on the low cost lockdown scenarios plots - many sims will take a long time, change simulations to 50 to get a reasonable estimate
iter = 11
simulations = 1000
PlotData <- data.table() 
for (i in 1:iter) {
  a <- Sys.time()
  Results <- SelfIsolationGame(HighIncomeLockdown, OwnStrategies,
                    c(rep("Defector", (10-(i-1))), rep("Unconditional Cooperator", (i-1))),
                    simulations)
  PlotData <- rbind(PlotData, Results %>% filter(PlayerNumber == 1) %>% mutate(Number_of_Defectors = (10-(i-1))))
  cat(i,"out of", iter, "iterations complete.\n")
  b <- Sys.time()
  print(b-a)
  
}


PlotDFLowCost <- PlotData %>% 
  group_by(Number_of_Defectors, OwnStrategy) %>% 
  filter(PlayerNumber == 1) %>%
  summarise(CumulativeIncome = mean(CumulativeIncomes)) %>% 
  ungroup() %>% 
  mutate(OwnStrategy = factor(OwnStrategy, levels=c("Defector", "Slight Cooperator",
                                                    "Moderate to None", "Moderate Cooperator", 
                                                    "Moderate to Complete", "Stringent Cooperator", 
                                                    "Unconditional Cooperator")),
         Number_of_Defectors = factor(Number_of_Defectors))

  
# Running for loop on the high cost scenarios
PlotData <- data.table() 
for (i in 1:iter) {
  a <- Sys.time()
  Results <- SelfIsolationGame(LowIncomeLockdown, OwnStrategies,
                    c(rep("Defector", (10-(i-1))), rep("Unconditional Cooperator", (i-1))),
                    simulations)
  PlotData <- rbind(PlotData, Results %>% filter(PlayerNumber == 1) %>% mutate(Number_of_Defectors = (10-(i-1))))
  cat(i,"out of", iter, "iterations complete.\n")
  b <- Sys.time()
  print(b-a)
  
}

PlotDFHighCost <- PlotData %>% 
  group_by(Number_of_Defectors, OwnStrategy) %>% 
  filter(PlayerNumber == 1) %>%
  summarise(CumulativeIncome = mean(CumulativeIncomes)) %>% 
  ungroup() %>% 
  mutate(OwnStrategy = factor(OwnStrategy, levels=c("Defector", "Slight Cooperator",
                                                    "Moderate to None", "Moderate Cooperator", 
                                                    "Moderate to Complete", "Stringent Cooperator", 
                                                    "Unconditional Cooperator")),
         Number_of_Defectors = factor(Number_of_Defectors))

#make a sound when done
beepr::beep()
```



```{r Plots}

LowCostStaticStrategies <- 
  ggplot(PlotDFLowCost %>% 
           filter(!OwnStrategy %in% c("Moderate to Complete", "Moderate to None")), 
         aes(x = Number_of_Defectors, y = CumulativeIncome, col = OwnStrategy, group = OwnStrategy)) +
  geom_point() +
  geom_line() + 
  scale_color_viridis_d(begin = .2, end = .85) +
  labs(title = "Low cost of lockdown", x = "Number of defectors", 
       y = "Income in points during game", col = "Own strategy") +
  lims(y = c(500, 2000)) +
  theme_light() + 
  theme(plot.title = element_text(size = 12))

HighCostStaticStrategies <- 
  ggplot(PlotDFHighCost %>% 
           filter(!OwnStrategy %in% c("Moderate to Complete", "Moderate to None")), 
         aes(x = Number_of_Defectors, y = CumulativeIncome, col = OwnStrategy, group = OwnStrategy)) +
  geom_point() +
  geom_line() + 
  scale_color_viridis_d(begin = .2, end = .85) +
  labs(title = "High cost of lockdown", x = "Number of defectors", 
       y = "Income in points during game", col = "Own strategy") +
  lims(y = c(500, 2000)) +
  theme_light() + 
  theme(plot.title = element_text(size = 12))


ggarrange(LowCostStaticStrategies, HighCostStaticStrategies, common.legend = T, legend = "bottom") +
  ggsave("StaticStrategiesPlot.png", height = 4, width = 9, dpi = "print")


LowCostDynamicStrategies <- 
  ggplot(PlotDFLowCost %>% 
           filter(!OwnStrategy %in% c("Slight Cooperator", "Stringent Cooperator")), 
         aes(x = Number_of_Defectors, y = CumulativeIncome, col = OwnStrategy, group = OwnStrategy)) +
  geom_point() +
  geom_line() + 
  scale_color_viridis_d(begin = .2, end = .85) +
  labs(title = "Low cost of lockdown", x = "Number of defectors", 
       y = "Income in points during game", col = "Own strategy") +
  lims(y = c(500, 2000)) +
  theme_light() + 
  theme(plot.title = element_text(size = 12))

HighCostDynamicStrategies <- 
  ggplot(PlotDFHighCost %>% filter(!OwnStrategy %in% c("Slight Cooperator", "Stringent Cooperator")), aes(x = Number_of_Defectors, y = CumulativeIncome, col = OwnStrategy, group = OwnStrategy)) +
  geom_point() +
  geom_line() + 
  scale_color_viridis_d(begin = .2, end = .85) +
  labs(title = "High cost of lockdown", x = "Number of defectors", 
       y = "Income in points during game", col = "Own strategy") +
  lims(y = c(500, 2000)) +
  theme_light() + 
  theme(plot.title = element_text(size = 12))

ggarrange(LowCostDynamicStrategies, HighCostDynamicStrategies, common.legend = T, legend = "bottom") +
  ggsave("DynamicStrategiesPlot.png", height = 4, width = 9, dpi = "print")

```
